Акутин И.Д. 6312 Лаб. 2
itsecd/prog-instruments-labs pull request #123
Opened 2024-11-04 13:04 UTC by Darktezi

**ФИО:** Акутин Игорь Дмитриевич 
**Номер группы:** 6312 
**Номер лабораторной:** 2
**Краткое описание исходного кода:** Я взял исходный код из интернета. Вот ссылка на него: https://github.com/NoeDam/TFE/blob/main/src/Final.py

2024-11-04 14:00 UTC, Darktezi commented on lab_2/Final.py
> +    dataframeN = dataframeN.assign(jobN = dataframe['job'].map(job_mapping))
Необходимо исправить длинну строк согласно PEP-8

2024-11-05 14:28 UTC, alxmcs requested changes

2024-11-05 14:28 UTC, alxmcs commented on lab_2/Final.py
> +    dataframeN = dataframe
А долго ли оперативка сможет вывозить создание глубокой копии датафрейма на каждый вызов функции?

2024-11-05 14:28 UTC, alxmcs commented on lab_2/Final.py
Хотелось бы получить некоторый комментарий насчет того, стоит ли оставлять весь имеющийся тут функционал - манипуляции датафреймом,  обучение и инференс классификаторов, демонстрацию графиков - в единственном модуле?

2024-11-05 14:28 UTC, alxmcs commented on lab_2/Final.py
> +    metric_svm = metric_privilege(df_svm)
Этот код выглядит подозрительно подходящим для того, чтобы параметризовать выбор классификатора. Хотелось бы увидеть небольшой пример кода, как это можно сделать

2024-11-05 16:48 UTC, Darktezi commented on lab_2/Final.py
> +    metric_svm = metric_privilege(df_svm)
Создаём словарь моделей с указанием на необходимость масштабирования. Функция станет короче и более гибкой, а так же необходимо сделать более понятное название для неё:
```
def train_and_evaluate_model(x_train, x_test, y_train, y_test):
    global df_original
    df_original = pd.DataFrame(x_test)
    df_original['yN'] = y_test

    scaler = StandardScaler()
    x_train_scaled = scaler.fit_transform(x_train)
    x_test_scaled = scaler.transform(x_test)

    classifiers = {
        "Naive Bayes": (MultinomialNB(), False),
        "Logistic Regression": (LogisticRegression(), True),
        "KNN": (KNeighborsClassifier(n_neighbors=20), True),
        "Random Forest": (RandomForestClassifier(n_estimators=100), True),
        "Neural Network": (MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, random_state=1), True),
        "SVM": (SVC(), False)
    }

    metrics_results = []

    for name, (model, use_scaling) in classifiers.items():
        x_train_data, x_test_data = (x_train_scaled, x_test_scaled) if use_scaling else (x_train, x_test)

        model.fit(x_train_data, y_train)
        y_pred = model.predict(x_test_data)

        df_result = pd.DataFrame(x_test)
        df_result['yN'] = y_pred

        metric = metric_privilege(df_result)
        metrics_results.append(metric)

    return metrics_results
```

2024-11-05 17:12 UTC, Darktezi commented on lab_2/Final.py
Для улучшении читаемости кода, тестируемости и поддерживаемости кода необходимо разделить код на несколько модулей. Например:
1. Модуль обработки данных
2. Модуль обучения моделей
3. Модуль оценки и метрик
4. Модуль визуализации

2024-11-05 17:18 UTC, Darktezi commented on lab_2/Final.py
> +    dataframeN = dataframe
функция вызывается один раз в maindeux(аналог main), поэтому я думаю что проблем с памятью быть не должно. Если функция maindeux будет вызываться многократно, то можно попробовать передать копию заранее, если это возможно:
`df_studentN = numerique(df_student.copy())`

2024-11-06 08:46 UTC, alxmcs approved these changes
Зачтено

2024-11-06 08:47 UTC, closed without merging