Ретивов Д.О. Лаб. 1 Группа 6312
itsecd/prog-instruments-labs pull request #132
Opened 2024-11-05 19:08 UTC by ynnmuraii

**ФИО:** Ретивов Данила Олегович
**Номер группы:** 6312 
**Номер лабораторной:** 1  
**Краткое описание исходного кода:** Я взял исходный код, реализующий текстовый редактор, из интернета. Вот ссылка на него: https://github.com/Mihey-Melnikov/text_editor.
**Краткое описание проделанной работы:** Я привёл код к стандартам PEP8.

2024-11-05 19:16 UTC, ynnmuraii commented
из за кривых рук удалил пол кода в предпоследнем коммите, поэтому продублировал

2024-11-06 08:57 UTC, alxmcs requested changes

2024-11-06 08:57 UTC, alxmcs commented on lab_1/main.py
> +from tkinter import Tk, Menu, LabelFrame, filedialog, messagebox, colorchooser, font, Text, Scrollbar, StringVar, END, INSERT, WORD
Эта строка явно превышает рекомендованную длину

2024-11-06 08:57 UTC, alxmcs commented on lab_1/main.py
> +import view
Обычно сначала идут директивы `import`, а потом `from`

2024-11-06 16:31 UTC, alxmcs approved these changes

2024-11-06 16:31 UTC, closed without merging