Шаменков М. А. Лаб. 5 Группа 6313
itsecd/prog-instruments-labs pull request #174
Opened 2024-11-19 12:54 UTC by Maximprogrammer58

**ФИО:** Шаменков Максим 
**Номер группы:** 6313
**Номер лабораторной:** 5 
**Краткое описание исходного кода:** Я взял исходный код из *своей старой лабораторной работы по прикладному программированию*. Вот ссылка на него: https://github.com/Maximprogrammer58/python_lab
**Краткое описание проделанной работы:** Я написал юнит-тесты на pytest. Продемонстрированы не только примитивные тесты, но и параметризованные тесты, моки. Результат работы тестов можно увидеть в файле [result.png](result.png).

2024-11-27 07:45 UTC, IlyaOv requested changes

2024-11-27 07:45 UTC, IlyaOv commented on lab_5/test_add_functions.py
> +def temp_data_file() -> Generator[str, None, None]:
Может имеет смысл сделать conftest.py, если фикстура используется не в 1 файле?

2024-11-30 17:48 UTC, Maximprogrammer58 commented on lab_5/test_add_functions.py
> +def temp_data_file() -> Generator[str, None, None]:
Исправил

2024-12-03 14:52 UTC, IlyaOv approved these changes
Зачтено

2024-12-03 14:52 UTC, closed without merging