Сулейманян А.В. Лаб. 2 Группа 6312
itsecd/prog-instruments-labs pull request #204
Opened 2024-11-26 19:40 UTC by bonyfa

ФИО: Сулейманян Арсен Владимирович
Номер группы: 6312
Номер лабораторной: 2
Краткое описание исходного кода: Я взял исходный код из интернета. Вот ссылка на него:
https://github.com/marcoemrich/Refactoring-Katas/blob/master/Tennis/python/tennis.py

2024-11-27 19:51 UTC, bonyfa commented on lab_2/tennis.py
> +    def __init__(self, player1Name, player2Name):
Нет тайпхинтов:  def __init__(self, player1Name: str, player2Name; str):

2024-11-27 20:00 UTC, bonyfa commented on lab_2/tennis.py
> +    def won_point(self, playerName):
Нет тайпхинтов и докстринга: won_point(self, playerName: str) -> None:
"""
    The function adds points to the winning player
    Parameters: self, playerName: str
    Return: None
 """

2024-11-27 20:21 UTC, bonyfa commented on lab_2/tennis.py
> +    def P2Score(self):
Нет докстринга, возвращающего значения: 
 def P2Score(self) -> None:
"""
player 2 score
Return: result: None
"""

2024-11-27 20:21 UTC, bonyfa commented on lab_2/tennis.py
> +    def P1Score(self):
Нет докстринга, , возвращающего значения: 
 def P1Score(self) -> None:
"""
player 1 score
Return: result: None
"""

2024-11-27 20:21 UTC, bonyfa commented on lab_2/tennis.py
> +    def SetP2Score(self, number):
Нет докстринга, тайпхинтов, возвращающего значения: 
 def SetP2Score(self, number: int) -> None:
"""
player 2 score
Parameters: self number: int
Return: result: None
"""

2024-11-27 20:21 UTC, bonyfa commented on lab_2/tennis.py
> +    def SetP1Score(self, number):
Нет докстринга, тайпхинтов, возвращающего значения: 
 def SetP1Score(self, number: int) -> None:
"""
player 1 score
Parameters: self number: int
Return: result: None
"""

2024-11-27 20:21 UTC, bonyfa commented on lab_2/tennis.py
> +    def score(self):
Нет докстринга, возвращающего значения: 
def score(self) -> dict:
"""

The function calculates the score
Parameters: self
Return: result: dict
"""

2024-11-27 20:21 UTC, bonyfa commented on lab_2/tennis.py
> +    def won_point(self, playerName):
Нет тайпхинтов и докстринга: won_point(self, playerName: str) -> None:
"""
The function adds points to the winning player
Parameters: self, playerName: str
Return: None
"""

2024-11-27 20:21 UTC, bonyfa commented on lab_2/tennis.py
> +    def __init__(self, player1Name, player2Name):
Нет тайпхинтов: def init(self, player1Name: str, player2Name; str):

2024-11-27 20:29 UTC, bonyfa commented on lab_2/tennis.py
> +        if (self.p1points == self.p2points and self.p1points < 4):
Тут и далее я бы поменял if , на словарь points = {
0 : "Love",
1 : "Fifteen",
2 : "Thirty",
3 : "Forty",
}
B if поменял бы на result = points[self.p1points]

2024-11-27 20:29 UTC, bonyfa commented on lab_2/tennis.py
> +    def won_point(self, n):
Нет тайпхинтов, докстринга, возвращаемого значения:
def won_point(self, n: int) -> None:

"""
The function adds points to the winning player
Parameters: self, n: int
Return: None
"""

2024-11-27 20:29 UTC, bonyfa commented on lab_2/tennis.py
> +    def score(self):
Нет докстринга, возвращающего значения:
def score(self) -> str:
"""

The function calculates the score
Parameters: self
Return: result: str
"""

2024-11-27 20:29 UTC, bonyfa commented on lab_2/tennis.py
> +    def __init__(self, player1Name, player2Name):
Нет тайпхинтов: def init(self, player1Name: str, player2Name; str):

2024-11-27 20:31 UTC, bonyfa reviewed
Добавил комментарии с исправлением кода

2024-11-28 08:08 UTC, alxmcs requested changes
1. Не надо добавлять комментарии к ревью через single comment
2.  Для разметки кода в маркдауне используется `а не "
3. Это ката для рефакторинга, а в ревью присутствуют только комментарии насчет докстрингов и тайпхинтов. Очевидные code smells, которые как раз в ходе рефакторинга этой каты надо исправить во всех трех ее имплементациях, никаким образом в ревью не описаны.

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def __init__(self, player1Name, player2Name):
Нет тайпхинтов:
def init(self, player1Name: str, player2Name; str):

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def score(self):
Нет докстринга, возвращающего значения:
def score(self) -> str:
`
The function calculates the score
Parameters: self
Return: result: str
`
Так же я бы сделал функцию score так
def score(self):
        if self.player1_points == self.player2_points:
            return self._equal_score()
        if self.player1_points >= 4 or self.player2_points >= 4:
            return self. self._equal_score()
        return self._regular_score()
Добавив еще 3 функции  self._equal_score()(Тут условия для ничьи),  self._equal_score()(условия для победы или преимущества в счете) и regular_score() (по той же логике)

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def won_point(self, playerName):
Нет тайпхинтов и докстринга:
won_point(self, playerName: str) -> None:
`
The function adds points to the winning player Parameters: self, playerName: str Return: None
`

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def __init__(self, player1Name, player2Name):
Нет тайпхинтов: def init(self, player1Name: str, player2Name; str):

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def won_point(self, playerName):
Нет тайпхинтов и докстринга: won_point(self, playerName: str) -> None:
`
The function adds points to the winning player
Parameters: self, playerName: str
Return: None
`

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def score(self):
Нет докстринга, возвращающего значения:
def score(self) -> str:
`
The function calculates the score
Parameters: self
Return: result: str
`

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +        if (self.p1points == self.p2points and self.p1points < 4):
Тут и далее я бы поменял if , на словарь points = {
0 : "Love",
1 : "Fifteen",
2 : "Thirty",
3 : "Forty",
}
B if поменял бы на result = points[self.p1points]

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +        if (self.p1points > 0 and self.p2points==0):
Тут и далее я бы поменял if , на словарь points = {
0 : "Love",
1 : "Fifteen",
2 : "Thirty",
3 : "Forty",
}
B if поменял бы на  P1res = points[self.p1points]

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +        if (self.p2points > 0 and self.p1points==0):
Тут и далее я бы поменял if , на словарь points = {
0 : "Love",
1 : "Fifteen",
2 : "Thirty",
3 : "Forty",
}
B if поменял бы на  P1res = points[self.p2points]

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +            if (self.p1points==2):
Тут и далее я бы поменял if , на словарь points = {
0 : "Love",
1 : "Fifteen",
2 : "Thirty",
3 : "Forty",
}
B if поменял бы на P1res = points[self.p1points]

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +        if (self.p2points>self.p1points and self.p2points < 4):
Тут и далее я бы поменял if , на словарь points = {
0 : "Love",
1 : "Fifteen",
2 : "Thirty",
3 : "Forty",
}
B if поменял бы на P1res = points[self.p2points]

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +            if (self.p1points==2):
Нет смысла в этом условия , так как оно было раньше

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def SetP1Score(self, number):
Нет докстринга, тайпхинтов, возвращающего значения:
def SetP1Score(self, number: int) -> None:
`
player 1 score
Parameters: self number: int
Return: result: None
`

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def SetP2Score(self, number):
Нет докстринга, тайпхинтов, возвращающего значения:
def SetP2Score(self, number: int) -> None:
`
player 2 score
Parameters: self number: int
Return: result: None
`

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def P1Score(self):
Нет докстринга, , возвращающего значения:
def P1Score(self) -> None:
`
player 1 score
Return: result: None
`

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def P2Score(self):
Нет докстринга, возвращающего значения:
def P2Score(self) -> None:
`
player 2 score
Return: result: None
`

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def __init__(self, player1Name, player2Name):
Нет тайпхинтов: def init(self, player1Name: str, player2Name; str):

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def won_point(self, n):
Нет тайпхинтов, докстринга, возвращаемого значения:
def won_point(self, n: int) -> None:

`
The function adds points to the winning player
Parameters: self, n: int
Return: None
`

2024-12-08 23:58 UTC, bonyfa commented on lab_2/tennis.py
> +    def score(self):
Нет докстринга, возвращающего значения:
def score(self) -> str:
`
The function calculates the score
Parameters: self
Return: result: str
`

2024-12-09 08:48 UTC, alxmcs approved these changes

2024-12-09 08:48 UTC, alxmcs commented
Зачтено

2024-12-09 08:48 UTC, closed without merging