Косенко М.Р. 6312 Лаб. 3
itsecd/prog-instruments-labs pull request #226
Opened 2024-11-29 13:39 UTC by KosenkoMichael

**ФИО:** Косенко Михаил
**Номер группы:** 6312 
**Номер лабораторной:** 3  **Номер варианта(при наличии):** 40
**Краткое описание исходного кода:** Я взял .csv с google drive согласно варианту
**Краткое описание проделанной работы:** Была проведена валидация строк в файле с использованием регулярных выражений

2024-11-29 14:00 UTC, alxmcs requested changes

2024-11-29 14:00 UTC, alxmcs commented on lab_3/main.py
> +height_pattern = r"^([1-2]\.\d{2}|3\.00)$"
трехметровых людей не бывает

2024-11-29 14:00 UTC, alxmcs commented on lab_3/result.json
> +  "checksum": "049cadd602faa2495af6cd3f4f939eb6"
что наводит меня на мысль, что это значение появилось тут не совсем честным образом

2024-11-29 15:02 UTC, KosenkoMichael commented
для проверки я вывел все сточки, в которых несоответствие было именно по росту. Оказалось, что те, что подходят под общую маску - имеют именно точку, именно 2 цифры после нее, но имеют целую часть явно не нормальную (41 метр или что-то вроде), а в тех числах. которые больше 2.5, но меньше 3.0 ошибка в другом (>2 цифр  после точки или запятая вместо точки и т.д.) и они все равно игнорировались моим изначальным кодом. Я не плохой человек, мне просто повезло

2024-12-02 06:40 UTC, alxmcs approved these changes
Звучит все еще подозрительно, но предположим

2024-12-02 06:40 UTC, closed without merging