Литвинов Д.Е. Лаб. 2 Группа 6313
itsecd/prog-instruments-labs pull request #246
Opened 2024-12-02 18:26 UTC by n0v4to

ФИО: Литвинов Денис Евгеньевич
Номер группы: 6313
Номер лабораторной: 2
Краткое описание исходного кода: Я взял исходный код из интернета. Вот ссылка на него: https://github.com/krishna999/dynamo-sample-code/blob/main/test.py
Краткое описание проделанной работы: Я сделал ревью кода

2024-12-02 19:03 UTC, n0v4to commented on lab_2/lab_2.py
> +def getJobResults(api, jobId):
названия функций, переменных хотелось бы видеть везде в snake_case, ВО ВСЕМ коде разное написание: processRequest, find_Key_value_inrange, thisText_Table

2024-12-02 19:04 UTC, n0v4to commented on lab_2/lab_2.py
> +    if len(dd_table_name) <= 3:
что за магическое число? лучше сделать константу и использовать ее

2024-12-02 19:05 UTC, n0v4to commented on lab_2/lab_2.py
> +        lastBottom = 1
что за магическое число? лучше сделать константу и использовать ее

2024-12-02 19:07 UTC, n0v4to commented on lab_2/lab_2.py
> +    kv_pair = {}
в коде часто встречаются малоинформативные названия переменных, что такое kv_pair?

2024-12-02 19:08 UTC, n0v4to commented on lab_2/lab_2.py
> +    analysis = {}
переменная не используется, наверное ее стоит удалить

2024-12-02 19:09 UTC, n0v4to commented on lab_2/lab_2.py
> +    output = ""
переменная не используется, наверное ее стоит удалить

2024-12-02 19:10 UTC, n0v4to commented on lab_2/lab_2.py
> +    jobStatus = request['jobStatus']
переменная не используется, наверное ее стоит удалить

2024-12-02 19:11 UTC, n0v4to commented on lab_2/lab_2.py
> +    TextList = []
переменная не используется, наверное ее стоит удалить

2024-12-02 19:11 UTC, n0v4to commented on lab_2/lab_2.py
> +    dynamodb_client = getClient('dynamodb')
переменная не используется, наверное ее стоит удалить

2024-12-02 19:13 UTC, n0v4to commented on lab_2/lab_2.py
> +def lambda_handler(event, context):
у функций нет ни аннотаций типов, ни докстрингов
* длины строк докстрингов не больше 72 символов ;)

2024-12-06 19:23 UTC, IlyaOv requested changes
Все комментарии в основном связаны со стандартами кодирования. Хотелось бы увидеть также комментарии касаемо code smells, архитектуры кода и т.д.

2024-12-08 15:13 UTC, n0v4to commented on lab_2/lab_2.py
> +        processRequest(request)
не мешало бы добавить обработку ошибок в функцию, например:
try:
        print("Received event: " + json.dumps(event))

        for record in event.get('Records', []):
            try:
                message = json.loads(record['Sns']['Message'])
                print("Message: {}".format(message))

                request = {
                    "job_id": message['job_id'],
                    "jobTag": message['JobTag'],
                    "jobStatus": message['Status'],
                    "jobAPI": message['API'],
                    "bucketName": message['DocumentLocation']['S3Bucket'],
                    "objectName": message['DocumentLocation']['S3ObjectName'],
                    "outputBucketName": os.environ['OUTPUT_BUCKET']
                }

                print(f"Full path of input file is {request['bucketName']}/{request['objectName']}")
                process_request(request)
            except KeyError as e:
                logger.error(f"Missing key in message: {e}")
            except json.JSONDecodeError as e:
                logger.error(f"Failed to decode JSON message: {e}")
            except Exception as e:
                logger.error(f"Unexpected error processing record: {e}")
    except Exception as e:
        logger.error(f"Error in lambda_handler: {e}")

2024-12-08 15:13 UTC, n0v4to commented on lab_2/lab_2.py
> +    return finalJSON_allpage
аналогично с предыдущей функцией, не хватает обработки ошибок, как вариант:
    try:
        text_tract_client = get_client('textract', 'us-east-1')
        blocks = []
        response = text_tract_client.get_document_analysis(JobId=job_id)

        analysis = copy.deepcopy(response)
        while True:
            try:
                for block in response.get("Blocks", []):
                    blocks.append(block)

                if "NextToken" not in response:
                    break

                next_token = response["NextToken"]
                response = text_tract_client.get_document_analysis(
                    JobId=job_id,
                    NextToken=next_token
                )
            except KeyError as e:
                logger.error(f"KeyError while processing job results: {e}")
                break
            except ClientError as e:
                logger.error(f"AWS ClientError while fetching job results: {e}")
                raise

        analysis.pop("NextToken", None)
        analysis["Blocks"] = blocks

        total_pages = response.get('DocumentMetadata', {}).get('Pages', 0)
        if not total_pages:
            logger.warning("No pages found in document metadata.")
            return []

        final_json_all_page = []
        for i in range(total_pages):
            this_page = i + 1
            this_page_json = parsejson_inorder_perpage(analysis, this_page)
            final_json_all_page.append({'Page': this_page, 'Content': this_page_json})
            print(f"Page {this_page} parsed")

        return final_json_all_page

    except ClientError as e:
        logger.error(f"AWS ClientError in get_job_results: {e}")
        raise
    except KeyError as e:
        logger.error(f"KeyError in get_job_results: {e}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error in get_job_results: {e}")
        raise

2024-12-09 14:01 UTC, IlyaOv approved these changes
Зачтено

2024-12-09 14:02 UTC, closed without merging