Артанов А.В. Лаб.2 Группа 6312
itsecd/prog-instruments-labs pull request #262
Opened 2024-12-04 15:59 UTC by vartanchik12

**ФИО:** Артанов Александр Викторович
**Номер группы:** 6312 
**Номер лабораторной:** 2 
**Краткое описание исходного кода:** Я взял(а) исходный код из интернета. Вот ссылка на него: https://github.com/marcoemrich/Refactoring-Katas/blob/master/Tennis/python/tennis.py https://github.com/emilybache/CustomerSync-Refactoring-Kata/blob/main/python/src/customer_data_access.py

2024-12-04 16:34 UTC, vartanchik12 reviewed
Код приведен к pep8, указаны проблемы

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_1.py
> +    def loadCompanyCustomer(self, externalId, companyNumber):
добавить typehints, docstrings, изменить название на snake_case

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_1.py
> +        matchByExternalId: Customer = self.customerDataLayer.findByExternalId(externalId)
изменить название на snake_case

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_1.py
> +    def loadPersonCustomer(self, externalId):
добавить tipehints, docstrings, изменить название на snake_case

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_1.py
> +        matchByPersonalNumber: Customer = self.customerDataLayer.findByExternalId(externalId)
изменить название на snake_case

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_1.py
> +    def updateCustomerRecord(self, customer):
добавить tipehints, docstrings, изменить название на snake_case

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_1.py
> +    def findByExternalId(self, externalId):
добавить tipehints, docstrings, изменить название на snake_case

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_1.py
> +    def findByCompanyNumber(self, companyNumber):
добавить tipehints, docstrings, изменить название на snake_case

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_1.py
> +    def updateCustomerRecord(self, customer):
добавить tipehints, docstrings, изменить название на snake_case

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_1.py
> +    def _find_addressId(self, customer):
Метод _find_addressId возвращает None, если адрес не найден. В этом случае следующий вызов fetchone может вызвать ошибку.

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_1.py
> +    def has_duplicates(self):
можно заменить просто на проверку bool(self.duplicates)

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_2.py
> +    def won_point(self, playerName):
добавить tipehints, docstrings

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_2.py
> +    def score(self):
добавить tipehints, docstrings

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_2.py
> +            for i in range(1,3):
создаёт дублирование кода при вычислении счёта для обоих игроков.

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_2.py
> +    def won_point(self, playerName):
Если игрок, которого нет, передан в won_point, это может вызвать ошибку

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_2.py
> +    def SetP1Score(self, number):
добавляет усложнение без необходимости

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_2.py
> +    def SetP2Score(self, number):
добавляет усложнение без необходимости

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_2.py
> +            return "Advantage " + s if ((self.p1-self.p2)*(self.p1-self.p2) == 1) else "Win for " + s
условие неочевидно

2024-12-04 16:34 UTC, vartanchik12 commented on lab_2/lab2_2.py
> +        self.p2 = 0
Переменные не информативны

2024-12-05 09:41 UTC, alxmcs requested changes
Надо расписать некоторые комментарии в ревью подробнее

2024-12-05 09:41 UTC, alxmcs commented on lab_2/lab2_2.py
> +    def SetP1Score(self, number):
Это крайне общая формулировка, надо расписать подробнее

2024-12-05 09:41 UTC, alxmcs commented on lab_2/lab2_2.py
> +    def SetP2Score(self, number):
Это крайне общая формулировка, надо расписать подробнее

2024-12-05 09:41 UTC, alxmcs commented on lab_2/lab2_2.py
> +            return "Advantage " + s if ((self.p1-self.p2)*(self.p1-self.p2) == 1) else "Win for " + s
Какой-то сомнительный аргумент. Тут нужно либо расписать подробнее, что подразумевается.
Либо смириться с тем, что условие оказалось не таким очевидным, как ты рассчитывал, если код рабочий 🤷‍♂️

2024-12-05 17:25 UTC, vartanchik12 reviewed
Исправил недочеты

2024-12-05 17:25 UTC, vartanchik12 commented on lab_2/lab2_2.py
> +    def SetP1Score(self, number):
Метод дублирует функциональность метода P1Score, просто вызывая метод этот метод несколько раз

2024-12-05 17:25 UTC, vartanchik12 commented on lab_2/lab2_2.py
> +    def SetP2Score(self, number):
Метод дублирует функциональность метода P2Score, просто вызывая метод этот метод несколько раз

2024-12-05 17:25 UTC, vartanchik12 commented on lab_2/lab2_2.py
> +            return "Advantage " + s if ((self.p1-self.p2)*(self.p1-self.p2) == 1) else "Win for " + s
Вместо вычисления квадрата разницы для определения равна ли абсолютная разница 1, можно было использовать модуль, чтобы более явно покажет цель проверки. abs(self.p1 - self.p2) == 1

2024-12-06 12:00 UTC, alxmcs commented
Зачтено

2024-12-06 12:00 UTC, closed without merging