Цыганова Д.А. Лаб.4 6313
itsecd/prog-instruments-labs pull request #285
Opened 2024-12-07 18:46 UTC by tsda04

**ФИО:** Цыганова Дарья
**Номер группы:** 6311  
**Номер лабораторной:** 4  
**Краткое описание исходного кода:** Я взяла исходный код из своей флешки. Это исходный код лаунчера терминальных игр. В нём находятся 5 простых игр, чтобы их запустить нужно в терминале запустить лаунчер и следовать подсказкам. Игры: Лабиринт, Виселица, 2048, крестики-нолики, угадай число.
**Краткое описание проделанной работы:** Я сделала логирование кода.

2024-12-09 15:15 UTC, IlyaOv requested changes

2024-12-09 15:15 UTC, IlyaOv commented on lab_4/launcher.py
> +        logging.info(f"Попытка запустить игру: {selected_game}")
Почему решили поменять способ форматирования строк при логировании?
Предлагаю остановиться на %.
https://docs.python.org/3/howto/logging.html#optimization
https://docs.python.org/3/howto/logging-cookbook.html#formatting-styles

2024-12-09 16:38 UTC, tsda04 commented on lab_4/launcher.py
> +        logging.info(f"Попытка запустить игру: {selected_game}")
прочитала документацию. действительно, исправленный вариант форматирования более предпочтительный, так как обеспечивает лучшую производительность и совместимость, чем форматирование с помощью f-строк.

2024-12-10 10:08 UTC, IlyaOv approved these changes
Зачтено

2024-12-10 10:08 UTC, closed without merging