Белякова У. А. Лаб. 2 Группа 6313
itsecd/prog-instruments-labs pull request #288
Opened 2024-12-08 14:00 UTC by ubeL13

ФИО: Белякова Ульяна Александровна
Номер группы: 6313
Номер лабораторной: 2
Краткое описание исходного кода: Это ранняя экспериментальная попытка создания тг бота. (https://github.com/ubeL13/bot)
Краткое описание проделанной работы: Сделала ревью кода, написал рекомендации для понятности и читабельности кода

2024-12-08 14:38 UTC, ubeL13 commented on lab_2/main.py
> +
Не соответствует PEP 8. Нужно импортировать модули в алфавитном порядке

2024-12-08 14:38 UTC, ubeL13 commented on lab_2/main.py
> +        except ValueError:
Не соответствует SOLID. Добавить блоки try-except, чтобы обрабатывать возможные ошибки.

2024-12-08 14:38 UTC, ubeL13 commented on lab_2/main.py
> +                         photo=open("images/start.png", "rb"),
Не соответствует DRY. Значения, такие как "images/start.png", следует вынести в константы или конфигурационный файл.

2024-12-08 14:38 UTC, ubeL13 commented on lab_2/main.py
> +    await message.answer(worker_text, reply_markup=markup_worker)
Не соответствует DRY. Дублирование кода в обработке колбеков worker_ref и worker_buy, можно создать вспомогательную функцию для редактирования сообщения.

2024-12-08 14:38 UTC, ubeL13 commented on lab_2/main.py
> +    await bot.send_message(text=worker_buy_text, chat_id=call.message.chat.id)
Не соответствует DRY. Дублирование кода в обработке колбеков worker_ref и worker_buy, можно создать вспомогательную функцию для редактирования сообщения.

2024-12-08 14:38 UTC, ubeL13 commented on lab_2/main.py
> +        pass
Не соответствует SOLID. Эта функция также выполняет несколько задач:
Отправляет ответ на колбек.
Отправляет сообщение или редактирует его.
Надо разбить функции на более мелкие, чтобы они выполняли одну задачу.

2024-12-08 14:38 UTC, ubeL13 commented on lab_2/main.py
> +                         photo=open("images/start.png", "rb"),
Не соответствует PEP 8.Следует использовать with open(...) as file вместо open для открытия файлов

2024-12-08 14:38 UTC, ubeL13 commented on lab_2/main.py
> +@dp.callback_query_handler(lambda call: 'promo' in call.data)
Не соответствует PEP 8. Нужно добавить аннотации типов для всех функций, чтобы улучшить читаемость и понимание кода.

2024-12-08 14:38 UTC, ubeL13 commented on lab_2/main.py
> +bot = Bot(token=API_TOKEN)
Не соответствует Solid. Неявная зависимость от глобальной переменной

2024-12-10 10:06 UTC, IlyaOv requested changes

2024-12-10 10:06 UTC, IlyaOv commented on lab_2/main.py
> +    await bot.send_photo(chat_id=call.message.chat.id, photo=pic, caption=s8_text, reply_markup=markup_s8)
С дублирование кода вроде этого что-то можно сделать?

2024-12-11 19:54 UTC, ubeL13 commented on lab_2/main.py
> +    await bot.send_photo(chat_id=call.message.chat.id, photo=pic, caption=s8_text, reply_markup=markup_s8)
Каждая функция практически идентична, поэтому можно создать одну универсальную функцию, которая будет обрабатывать все вызовы. Принимать параметры, такие как номер кнопки, текст и разметка; И для хранения параметров, связанных с каждым состоянием, можно использовать словарь.
```
@dp.callback_query_handler(lambda call: call.data in ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8'])
async def send_photo(call: types.CallbackQuery):
    await bot.answer_callback_query(call.id)
    
    photo_data = {
        's1': ("images/s1.jpg", s1_text, markup_s1),
        's2': ("images/s2.jpg", s2_text, markup_s2),
        's3': ("images/s3.jpg", s3_text, markup_s3),
        's4': ("images/s4.jpg", s4_text, markup_s4),
        's5': ("images/s5.jpg", s5_text, markup_s5),
        's6': ("images/s6.jpg", s6_text, markup_s6),
        's7': ("images/s7.jpg", s7_text, markup_s7),
        's8': ("images/s8.jpg", s8_text, markup_s8),
    }
    
    pic_path, caption, markup = photo_data[call.data]
    
    with open(pic_path, "rb") as pic:
        await bot.send_photo(chat_id=call.message.chat.id, photo=pic, caption=caption, reply_markup=markup)
```

2024-12-12 10:34 UTC, closed without merging