Дьячков К. А. Лаб. 1 Группа 6311
itsecd/prog-instruments-labs pull request #290
Opened 2024-12-08 14:13 UTC by feelpainagain

**ФИО:** Дьячков Кирилл
**Номер группы:** 6311  
**Номер лабораторной:** 1 
**Краткое описание исходного кода:** Я взял исходный код из интернета. Вот ссылка на него: https://github.com/icepick4/Sonic-Game/blob/main.
**Краткое описание проделанной работы:** Я сделал рефакторинг.

2024-12-09 16:23 UTC, IlyaOv requested changes

2024-12-09 16:23 UTC, IlyaOv commented on lab_1/main.py
> +pygame.display.quit()
Почему-то резкий переход произошел к функциям, но да ладно.
В итоге пустая строка в конце документа пропала.

2024-12-11 20:46 UTC, feelpainagain commented on lab_1/main.py
> +pygame.display.quit()
Касаемо пустой строки, к сожалению, как оказалось гитхаб не отображает пустую строку в конце документов, поэтому прилагаю скриншот того, что она на самом деле есть...
![image](https://github.com/user-attachments/assets/1d816ce4-8e4f-4f3c-bb59-933e5b6a0161)

2024-12-12 10:39 UTC, IlyaOv approved these changes
Зачтено

2024-12-12 10:39 UTC, closed without merging