Чуева Мария Лаб. 5 Группа 6312
itsecd/prog-instruments-labs pull request #359
Opened 2024-12-13 21:06 UTC by Lisyonok04

ФИО: Чуева Мария  
Номер группы: 6312  
Номер лабораторной: 5 
Краткое описание исходного кода: За основу для покрытия тестами был взят исходный код из своей старой лабораторной работы по курсу ОИБ. Ссылка на него: https://github.com/Lisyonok04/lab1-var5/tree/lab3-var4
Краткое описание проделанной работы: Были добавлены pytest, покрывающие большую часть функционала кода. В некоторых тестах было использовано параметризированное тестирование.

2024-12-13 21:21 UTC, Lisyonok04 commented
Затрудняюсь сказать, почему помимо проверки 5-ой лабораторной работы проверяется и 3-я. Но по поводу ошибки в unit-test могу привести доказательства, что все работает и запускается корректно на ноутбуке:
![тесты](https://github.com/user-attachments/assets/b01cbe40-15f1-4b7e-a9bf-0c863e66b820)

2024-12-14 09:57 UTC, alxmcs requested changes
Необходимые модули не устанавливаются, потому что requirements.txt лежит во вложенной в lab_5 директории, а не в самой lab_5
![image](https://github.com/user-attachments/assets/902daa56-81dd-451e-9646-3f51dcb84d13)
![image](https://github.com/user-attachments/assets/00fcbd64-cbd1-4363-9fa6-138b8061fdcf)
Попробуй поместить весь код лабораторной непосредственно в директорию `lab_5`

2024-12-16 10:57 UTC, alxmcs approved these changes
👍 
![image](https://github.com/user-attachments/assets/065dca96-4705-4786-9060-80d39fcae570)

2024-12-16 10:58 UTC, alxmcs commented
Зачтено

2024-12-16 10:58 UTC, closed without merging