ЗубковД.О. Лаб. 4 Группа 6312
itsecd/prog-instruments-labs pull request #367
Opened 2024-12-14 15:28 UTC by den3yb

ФИО: Зубков Денис Олегович
Номер группы: 6312
Номер лабораторной: 2 Номер варианта(при наличии): -
Краткое описание исходного кода: Взял код из своей старой лабораторной работы
Краткое описание проделанной работы: Добавил в moduls новый модуль с logger, сделал реализацию

2024-12-16 10:47 UTC, alxmcs requested changes
Местами выглядит, как будто у автора кода произошел инсульт

2024-12-16 10:47 UTC, alxmcs commented on lab_4/moduls/reader_writer.py
> +            logger.warning("Возникла ошибка при сиреализацииЭ приватного ключа: ", e)
>сиреализацииЭ

2024-12-16 10:47 UTC, alxmcs commented on lab_4/moduls/cryptography.py
> +        logger.info("Запуск процедкры генерации и сериализации ключей")
>процедкры

2024-12-16 10:47 UTC, alxmcs commented on lab_4/moduls/cryptography.py
> +        logger.info("Произогло создание асимметричного ключа")
>Произогло

2024-12-16 10:47 UTC, alxmcs commented on lab_4/moduls/cryptography.py
> +        logger.info("Произошла шифровка симметричного ключа")
> шифровка 

Может, все-таки, произошло *шифрование*?

2024-12-16 10:47 UTC, alxmcs commented on lab_4/moduls/symetric.py
> +        """Выолняется дешифрование текста, принимается зашифрованный текст в байтах и ключ, возвращает расшифрованный текст строкой"""
>Выолняется

2024-12-16 10:47 UTC, alxmcs commented on lab_4/moduls/symetric.py
> +        """Выполняетя шифрования текста, получает текст строкой и ключ, возвращает зашифрованный текст в байтах"""
>Выполняетя шифрования

2024-12-16 18:35 UTC, den3yb commented
Орфографические инсульты иногда случаются, извините

2024-12-17 07:59 UTC, alxmcs approved these changes

2024-12-17 07:59 UTC, alxmcs commented
Зачтено

2024-12-17 07:59 UTC, closed without merging