Ульянов А.М. Лаб.5 Группа 6312
itsecd/prog-instruments-labs pull request #376
Opened 2024-12-15 09:39 UTC by Sanechek600

**ФИО:** Ульянов А.М.  
**Номер группы:** 6312  
**Номер лабораторной:** 5
**Краткое описание исходного кода:** Исходный код от 4 лабораторной ТМП https://github.com/Sanechek600/prog-instruments-labs/tree/lab4/lab_4
**Краткое описание проделанной работы:** Написал юнит-тесты, проверяющие работу NIST-тестов, проверяющих работу ГПСЧ в Java и C++.

2024-12-15 10:09 UTC, Sanechek600 commented
Вот уж не знаю, почему у бота тесты проваливаются, а у меня проходят
![image](https://github.com/user-attachments/assets/2b35ed69-a2d5-4c80-bb82-ff04c4ab7651)

2024-12-16 10:27 UTC, alxmcs requested changes

2024-12-16 10:27 UTC, alxmcs commented on lab_5/res_test.py
> +    assert pytest.approx(frequency) == longest_run_of_ones_test(c_sequence)
Потому что дефолтного толеранса в 1e-6 оказывается недостаточно:
![image](https://github.com/user-attachments/assets/b9fb60c7-a6f5-42d3-858b-2d797b10031f)
Тебе придется выставить его вручную

2024-12-16 11:06 UTC, alxmcs approved these changes
Не в тот лог раннера глянул, оказывается все уже починено

2024-12-16 11:06 UTC, closed without merging