Ретивов Д.О. 6312 Лаб. 2
itsecd/prog-instruments-labs pull request #38
Opened 2024-10-03 08:47 UTC by alxmcs

**ФИО:** Ретивов Д.О. @ynnmuraii
**Номер группы:** 6312  
**Краткое описание исходного кода:** Это на редкость отвратительная имплементация 3 лабораторной по ОИБ, написанная много лет назад студентом, имя которого разглашать не будем. Думаю, все проблемы этого кода достаточно очевидны.

2024-11-10 17:45 UTC, ynnmuraii commented on lab_2/main.py
> +import yaml
Нужно сгруппировать вызов библиотек в одну-две строки, например ```from cryptography.hazmat.primitives.asymmetric import rsa, hashes, padding```

Лучше более конкретно вызывать ```padding2```, иначе можно легко спутать с ```padding```

Где используется ```tqdm_notebook```? Нигде. Надо удалить.

Ну и в целом нужно группировать блоки.

2024-11-10 17:55 UTC, ynnmuraii commented on lab_2/main.py
> +        prograssbar.update(100)
Вынести ```argparse``` в отдельный файл, декомпотизировать код. В разных файлах разные функции.

2024-11-10 17:57 UTC, ynnmuraii commented on lab_2/main.py
> +    """
Функция содержит много операций, что делает её сложно читаемой и тестируемой. Нужно декомпозировать функцию на меньшие функции: ```generate_symmetric_key()```, ```serialize_key_to_file()``` и т.д.

2024-11-10 17:57 UTC, ynnmuraii commented on lab_2/main.py
> +    with tqdm(100, desc='Generation keys') as prograssbar:
Может быть тут имелось в виду ```progressbar```?

2024-11-10 17:58 UTC, ynnmuraii commented on lab_2/main.py
> +                                                                label=None))
Вынести в отдельную функцию.

2024-11-10 18:00 UTC, ynnmuraii commented on lab_2/main.py
> +    """
То же самое, что и с ```key_generation```: разбить на маленькие функции.

2024-11-10 18:01 UTC, ynnmuraii commented on lab_2/main.py
> +        content_encrypted = yaml.safe_load(_file)
Процесс десериализации повторяется с 73-82 строки. Вынести в отдельные функции, чтобы не повторять код и не делать его громоздким.

2024-11-10 18:04 UTC, ynnmuraii commented on lab_2/main.py
> +        public_pem = public_key_path + '\\key.pem'
Используется абсолютный путь, как и во всём остальном коде. Лучше использовать ```os.path``` для работы с путями.

2024-11-10 18:14 UTC, ynnmuraii commented on lab_2/main.py
> +    private_key = load_pem_private_key(private_bytes, password=None)
Повторение существующего кода. Вынести в отдельные функции.

2024-11-10 18:14 UTC, ynnmuraii requested changes
Помимо отдельно озвученных проблем, есть ещё несколько глобальных: 

1. Код не соответствует PEP8 (отступы; длина строк, превышающая лимит 79; опечатки и т.д.)
2. Полностью отсутствует обработка исключений. 
3. Полностью отсутствует логирование. Без него тестировать и проверять код сложно.

Для улучшения структурированности и читаемости кода, имеет смысл разбить его на несколько модулей, каждый из которых будет выполнять отдельные задачи. Предлагаю разбить на следующие модули:
- ```main.py```
- ```key_generation.py```
- ```encryption.py```
- ```decryption.py```
- ```utils.py```

2024-11-15 10:13 UTC, alxmcs reviewed
Зачтено

2024-11-15 10:13 UTC, closed without merging