Лутфуллин Г.А. Лаб 2. Группа 6312
itsecd/prog-instruments-labs pull request #395
Opened 2024-12-16 00:15 UTC by downmeansoff

**ФИО:** Лутфуллин Глеб
**Номер группы:** 6312
**Номер лабораторной работы:** 2
**Краткое описание исходного кода:** Я взял исходный код из своей старой лабораторной работы
**Краткое описание проделанной работы:** Я сделал ревью.

2024-12-16 01:11 UTC, downmeansoff reviewed
Для начала **декомпозировать функцию**, убрать **пустые строки**, добавить **argparse**, **docstrings(PEP-257)**. (Рекомендуется усовершенствовать графики, например : добавить сетку для улучшения читаемости графиков.) После этих шагов отправить код на повторный ревью.

2024-12-16 09:41 UTC, alxmcs requested changes

2024-12-16 09:41 UTC, alxmcs commented on lab_2/main.py
> +    plt.show()
Предложить вариант декомпозиции этого фрагмента для избегания дублирования кода

2024-12-17 08:57 UTC, downmeansoff commented on lab_2/main.py
> +    plt.show()
Вариант декомпозиции этого фрагмента для избегания дублирования кода : 
```
def plot_time_series(data, column, title, subplot_position):
    plt.subplot(2, 2, subplot_position)
    plt.plot(data['Дата'], data[column], label=column)
    plt.axhline(y=data[column].median(), color='r', linestyle='--', label='Медиана')
    plt.axhline(y=data[column].mean(), color='g', linestyle='--', label='Среднее значение')
    plt.xlabel('Дата')
    plt.ylabel(column)
    plt.title(title)
    plt.legend()

plt.figure(figsize=(10, 8))

plot_time_series(filtered_data, 'Температура', 'График изменения температуры', 1)
plot_time_series(filtered_data, 'Давление', 'График изменения давления', 2)
plot_time_series(filtered_data, 'Ветер', 'График изменения скорости ветра', 3)

plt.tight_layout()
plt.show()
```

2024-12-17 11:00 UTC, alxmcs approved these changes

2024-12-17 11:01 UTC, alxmcs commented
Зачтено

2024-12-17 11:01 UTC, closed without merging