Цуненко В.А. 6312 Лаб. 2
itsecd/prog-instruments-labs pull request #40
Opened 2024-10-03 08:53 UTC by alxmcs

**ФИО:** Цуненко В.А. 
**Номер группы:** 6312  
**Краткое описание исходного кода:**  Это на редкость отвратительная имплементация 3 лабораторной по ОИБ, написанная много лет назад студентом, имя которого разглашать не будем. Думаю, все проблемы этого кода достаточно очевидны.

2024-10-24 17:47 UTC, Darowiin requested changes
А также в целом можно во все добавленные функции добавить блок try-except и в конце добавлять logging для выявления ошибок и использовать его для вывода данных вместо print-ов

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
Стоит группировать импорты по блокам: встроенные модули, сторонние библиотеки, а затем локальные
Между блоками нужна пустая строка

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +
Выполняемый код вынести в  `if __name__ == "__main__"`

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +with open('settings.json') as _file:
Название файла можно вынести в параметр argparse

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +with open('settings.json') as _file:
Также нужно обернуть это в блок try-except для обработки исключений

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +    print('Зашифрованно и записанно в файл symmetric.txt')
Вынести в отдельную функцию, например, key_generation

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +    key = os.urandom(16)
Длину ключа вынести в аргументы функции

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +    print('Зашифровали и сохранили текст в encrypted_file.txt')
Также вынести в функцию

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +    from cryptography.hazmat.primitives import padding
Импорт вынести в начало файла

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +    print('Текст расшифрован и сохранен в файл decrypted_file.txt')
Тоже в отдельную функцию

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +    from cryptography.hazmat.primitives import padding
Лишний импорт удалить

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +    d_private_key = load_pem_private_key(private_bytes, password=None, )
Повторяющийся код необходимо вынести в функцию
```
def load_rsa_keys(json_data):
    with open(json_data['public_key'], 'rb') as pem_in:
        public_bytes = pem_in.read()
    d_public_key = load_pem_public_key(public_bytes)
    with open(json_data['private_key'], 'rb') as pem_in:
        private_bytes = pem_in.read()
    d_private_key = load_pem_private_key(private_bytes, password=None, )
    return public_key, private_key
```

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +    d_private_key = load_pem_private_key(private_bytes, password=None, )
Повторяющийся код необходимо вынести в функцию
```
def load_rsa_keys(json_data):
    with open(json_data['public_key'], 'rb') as pem_in:
        public_bytes = pem_in.read()
    d_public_key = load_pem_public_key(public_bytes)
    with open(json_data['private_key'], 'rb') as pem_in:
        private_bytes = pem_in.read()
    d_private_key = load_pem_private_key(private_bytes, password=None, )
    return public_key, private_key
```

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +        cim_symmetric_key = symmetric_file.read()
Повторяющийся код необходимо вынести в функцию
```
def load_symmetric_key(json_data):
    with open(json_data['symmetric_key'], 'rb') as symmetric_file:
        return symmetric_file.read()
```

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +        d_symmetric_key = symmetric_file.read()
Повторяющийся код необходимо вынести в функцию
```
def load_symmetric_key(json_data):
    with open(json_data['symmetric_key'], 'rb') as symmetric_file:
        return symmetric_file.read()
```

2024-10-24 17:47 UTC, Darowiin commented on lab_2/main.py
> +    print('Текст расшифрован и сохранен в файл decrypted_file.txt')
Путь файла можно передавать в качестве параметра, в случае его изменения в json файле, тут путь также поменяется

2024-10-25 05:50 UTC, alxmcs commented on lab_2/main.py
Надо дополнить ревью комментарием насчет физической декомпозиции кода  - нужно ли разбивать данный модуль на несколько, на сколько именно, какие функции будет выполнять каждый отдельный модуль.

2024-10-25 10:30 UTC, Darowiin reviewed
Сейчас модуль выполняет сразу несколько задач - генерация ключей, шифрование, дешифрование и работа с файлами. Необходимо декомпозировать код на несколько модулей:

1. **Модуль для работы с шифрованием** (например, `encryption_utils.py`):
   - Все функции, связанные с генерацией ключей, шифрованием и дешифрованием.

2. **Модуль для работы с файлами** (например, `file_utils.py`):
   - Функции для чтения и записи файлов, сериализация и десериализация ключей.

3. **Основной модуль** (например, `main.py`):
   - Логика программы: обработка аргументов командной строки, вызов функций для шифрования и работы с файлами.

Такое разделение сделает код более читабельным и позволит переиспользовать логику шифрования и дешифрования в других частях приложения без необходимости дублирования кода.

2024-10-25 12:09 UTC, alxmcs commented
Зачтено

2024-10-25 12:09 UTC, closed without merging