ЗубковД.О. Лаб. 4 Группа 6312
itsecd/prog-instruments-labs pull request #406
Opened 2024-12-16 22:28 UTC by den3yb

ФИО: Зубков Денис Олегович
Номер группы: 6312
Номер лабораторной: 5 Номер варианта(при наличии): -
Краткое описание исходного кода: Взял код из своей старой лабораторной работы
Краткое описание проделанной работы: Добавил тесты чтобы протестировать функционал кода

2024-12-16 22:42 UTC, den3yb commented
Здравствуйте, проверка ругается на отсутствие модуля cryptography, xотя он есть в requirements.txt
![photo_5406793853895305604_w](https://github.com/user-attachments/assets/83020c9f-235f-4c9c-ba08-ffbcf4aab2b4)
![image](https://github.com/user-attachments/assets/7282e099-edc7-4b16-b4ea-6dcb31c4d91b)

2024-12-17 08:03 UTC, alxmcs requested changes

2024-12-17 08:03 UTC, alxmcs commented on requirements.txt
Этот файл должен лежать внутри директории lab_5

2024-12-17 08:48 UTC, alxmcs requested changes
У тебя conda используется в качестве энвайромента для приложения? в requirements.txt куча пакетов, основная часть которых явно не нужна для работы приложения, да и еще с локальными путями

Для работы акшона нужно указать только необходимые пакеты и их версии

2024-12-17 08:50 UTC, den3yb commented
Хорошо, сейчас исправлю

2024-12-17 10:56 UTC, alxmcs approved these changes

2024-12-17 10:57 UTC, alxmcs commented
Зачтено

2024-12-17 10:57 UTC, closed without merging