Яковлев Р.С. Лаб. 5 Группа 6312
itsecd/prog-instruments-labs pull request #432
Opened 2024-12-18 22:26 UTC by Ryedis

ФИО: Яковлев Радик Сергеевич
Номер группы: 6312
Номер лабораторной: 5
Краткое описание исходного кода: Я взял исходный код из своей старой лабораторной работы. Вот ссылка на него: https://github.com/Ryedis/isb/tree/lab2-var7
Краткое описание проделанной работы: Я сделал юнит-тесты, покрывающие основные функции моего кода.

2024-12-18 22:41 UTC, Ryedis commented
![изображение](https://github.com/user-attachments/assets/129535c3-f0f2-4d6e-8d80-07ef08c95d7c)

2024-12-19 08:12 UTC, alxmcs requested changes

2024-12-19 08:12 UTC, alxmcs commented on lab_5/lab_2/requirements.txt
Акшон ищет requirements.txt внутри lab_5, а не lab_5/lab_2

2024-12-19 09:14 UTC, alxmcs approved these changes

2024-12-19 09:15 UTC, alxmcs commented
Зачтено

2024-12-19 09:15 UTC, closed without merging