Старцева А.В. Лаб. 1 Группа 6313
itsecd/prog-instruments-labs pull request #57
Opened 2024-10-08 00:34 UTC by Annaprogrammer300

**ФИО:** Старцева Анна  
**Номер группы:** 6313  
**Номер лабораторной:** 1
**Краткое описание исходного кода:** Я взяла исходный код из репозитория знакомого старшекурсника ИБАСа. Вот ссылка на него: https://github.com/AvtoBBus/Bus_Station_4/tree/main.
**Краткое описание проделанной работы:** Я сделала рефакторинг не своего кода.

2024-10-14 16:18 UTC, Annaprogrammer300 commented
> Укажите пожалуйста к какому стандарту приводится код.
привожу к стандарту PEP8

2024-10-15 12:06 UTC, IlyaOv requested changes

2024-10-15 12:06 UTC, IlyaOv commented on lab_1/get_schedule.py
> +    :param selected_weekday: The day of the week for which to find the schedule.
Для строк документации и комментариев тоже есть рекомендации в PEP 8.

2024-10-18 19:59 UTC, Annaprogrammer300 commented
Если я правильно поняла то, что комментарии и строки документации будут до 72 символов, то скорректировала их в комите про длины строк

2024-10-19 13:32 UTC, IlyaOv approved these changes
Зачтено

2024-10-19 13:32 UTC, closed without merging