Lab 1
itsecd/prog-instruments-labs pull request #91
Opened 2024-10-28 16:41 UTC by derasoft004

**ФИО:** Зюзин Егор Вадимович  
**Номер группы:** 6313 
**Номер лабораторной:** 1  
**Краткое описание исходного кода:** Я взял исходный код из *своего старого пет-проекта, в котором разрабатывал telegram-бота будучи не очень опытным *. Вот ссылка на него: https://github.com/derasoft004/project_tgbot_inochiclub.git
**Краткое описание проделанной работы:**
В проекте я проделал множество изменений, начиная с изменения названий переменных и функций, заканчивая полно деструктуризацией и добавлением соответствующих модулей; заменил много строчек кода циклами, большинство текста поместил в .json файл для удобства хранения текстовых переменных, разделил функции, выполняющие различные задачи по группам.

2024-10-30 06:12 UTC, IlyaOv commented
Проделана важная работа, но первая лабораторная работа направлена на **стандарты кодирования**. Прочитайте, пожалуйста, условия ее сдачи.

2024-10-30 06:53 UTC, derasoft004 commented
> Проделана важная работа, но первая лабораторная работа направлена на **стандарты кодирования**. Прочитайте, пожалуйста, условия ее сдачи.

Я привел свой старый код к  **стандартам кодирования** PEP8, также структурировал плохо собранный проект, применил **Осмысленное название коммитов**, в каждом коммите исправлял разные аспекты (может слегка больше чем один), **Размер моего исходного кода блолее 300 строк**, применено 5 различных правил оформления кода: импорты  приведены к стандарту PEP;  добавлены нужные отступы по PEP8; добавлены файлы 'requirements.txt' и '.env' (а так же 'config.py'), что относится к правильному оформлению кода, так как секретные ключи и токены не должны содержаться в коде; повторяющиеся строки заменены более компактными выражениями; код избавлен от множества глобальных переменных, которые в этой области памяти находиться не должны. **В описании пул-риквеста ссылку на исходный источник редактируемого кода** указал. 
Что мне нужно поправить, добавить? Подскажите, пожалуйста.

2024-10-30 07:13 UTC, derasoft004 commented
ой там не type-scripts а type-hints 😃

2024-10-31 19:01 UTC, IlyaOv requested changes
Если приводится к PEP 8, то из вашего ответа и коммитов я пока увидел указание на 3 аспекта:
- оформление импортов
- отступы
- type hints

Их проверил, замечания написал. 

Остальное безусловно является хорошей практикой и естественно не возбраняется. (чему и посвящены другие лабораторные работы). Но, на мой взгляд, не относится непосредственно к PEP 8. Не утверждаю, что прав, приведите пример из документации, если ошибаюсь. Если это из других стандартов кодирования, укажите их.

Пока мне видится необходимость выбрать и поправить еще пару аспектов из PEP 8.

2024-11-03 09:46 UTC, derasoft004 commented
Исправил импорты по Вашему замечанию, поправил некоторые ветки с иф и условием в одной строке, поправил слишком длинные строки

2024-11-03 15:37 UTC, IlyaOv commented
Зачтено

2024-11-03 15:37 UTC, closed without merging