Зубков Д.О. 6312 Лаб. 2
itsecd/prog-instruments-labs pull request #97
Opened 2024-10-29 15:52 UTC by den3yb

ФИО: Зубков Денис Олегович
Номер группы: 6312
Номер лабораторной: 2 Номер варианта(при наличии): -
Краткое описание исходного кода: Взял код из своей лабораторной работы
Краткое описание проделанной работы: Выполнил ревью для кода

2024-10-30 09:02 UTC, alxmcs requested changes
Видимо, тут в скором времени должно появиться ревью на код в директории `lab_2`?

1. Удаление ридми влечет за собой изменения в директориях, на которые повешены github actions, лучше так не делать.

2. Зачем ты снес из ветки код 1 лабораторной, чтобы затем добавить код второй? Можно было просто добавить код для 2 лабораторной в отдельной ветке, основанной на мейне.

2024-10-30 15:33 UTC, den3yb commented
Здравствуйте, забыл отправить ревью.
1. Извините не знал что это так важно, больше не буду удалять
2. Я случайно сделал бранч от первой лабораторной работы, а не от мейна, забыл переключится

2024-10-31 11:12 UTC, alxmcs reviewed
В ревью есть фразы о том, что можно было бы применить ООП парадигму в этом коде. Хотелось бы, чтобы было поподробнее расписано, на какие классы (и с какими связями - композициями/агрегациями/наследованиями) можно декомпозировать код.
А также на какие модули его можно разбить (если в этом есть необходимость)

2024-11-10 21:00 UTC, den3yb commented
Я предлагаю разбить код по простому на следующие классы:
1) Класс для асимметричного ключа
     Поля: публичный и приватные ключи
     Методы:
     1.1 Генерация публичного и приватного ключей
     1.2 Шифрование симметричного ключа
     1.3 Дешифровка симметричного ключа
     1.4 Сериализация асимметричного ключа
     1.5 десериализация асимметричного ключа
 2) Класс для симметричного ключа
     Поля: симметричный ключ
     Методы:
     1.1 Генерация симметричного ключа
     1.2 Шифрование текста
     1.3 Дешифровка текста
     1.4 Сериализация симметричного ключа
     1.5 Десериализация симметричного ключа
 3) Класс, содержащий все операции записывания/считывания
     Поля: либо отсутствуют, либо адреса файлов
     Методы:
     1.1 Чтение текста из файла
     1.2 Запись текста в файл
     1.3 Считывание json файла
     
Это самой простой вариант, но если заморачиваться то можно использовать агрегацию на классах симметричного и асимметричного шифрования чтобы симметричный ключ являлся частью асимметричного, но мог существовать независимо от него. Так же часть методов сериализация которая касается записи в файл можно вынести в класс операция считывания и записи. 

Про деление на модули если мы реализуем агрегацию то симметричное и асимметричное шифрование мы выносим в отдельный модуль из-за связи, если без агрегации то в два отдельных модуля, а так же необходим модуль работы с текстом и модуль в котором у нас содержаться функции вызывающий процесс работы программы(generation_proc, encryption_proc, decryption_proc)

2024-11-15 10:15 UTC, closed without merging